/**
 * Одноразовое применение переименований классов (БЭМ) в HTML/CSS.
 * Запуск: node tools/apply-bem.cjs
 */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

const pairs = [
    ['.nav-links a.header-cta-btn.active::after', '.site-header__list .site-header__cta.site-header__cta--active::after'],
    ['.nav-links a.header-cta-btn.active', '.site-header__list .site-header__cta.site-header__cta--active'],
    ['.nav-links a.header-cta-btn', '.site-header__list .site-header__cta'],
    ['.header-cta-btn:not(.nav-links .header-cta-btn)', '.site-header__cta:not(.site-header__list .site-header__cta)'],
    ['.subject-detail.subject-detail-visible', '.services__detail.services__detail--visible'],
    ['.nav-dropdown.active-dropdown > a i.fa-chevron-down', '.site-header__dropdown.site-header__dropdown--open > a i.fa-chevron-down'],
    ['.nav-dropdown.active-dropdown .dropdown-menu', '.site-header__dropdown.site-header__dropdown--open .site-header__submenu'],
    ['.nav-dropdown:hover > a i.fa-chevron-down', '.site-header__dropdown:hover > a i.fa-chevron-down'],
    ['.nav-dropdown:hover .dropdown-menu', '.site-header__dropdown:hover .site-header__submenu'],
    ['.nav-dropdown .dropdown-menu', '.site-header__dropdown .site-header__submenu'],
    ['.nav-dropdown > a i.fa-chevron-down', '.site-header__dropdown > a i.fa-chevron-down'],
    ['.nav-dropdown > a:hover', '.site-header__dropdown > a:hover'],
    ['.nav-dropdown > a', '.site-header__dropdown > a'],
    ['events-more-wrapper:not(.events-more-wrapper--visible)', 'events__more:not(.events__more--visible)'],
    ['events-more-wrapper--visible .events-more-inner', 'events__more--visible .events__more-inner'],
    ['.events .slider-arrow:not(.slider-container .slider-arrow)', '.events .slider__arrow:not(.slider__container .slider__arrow)'],
    ['.events .slider-container', '.events .slider__container'],
    ['.slider-container .slider-dot.active', '.slider__container .slider__dot--active'],
    ['.slider-dot.active', '.slider__dot--active'],
    ['contact-form-wrapper', 'contact__form-wrap'],
    ['subjects-preview-wrapper', 'services__subjects-wrap'],
    ['subject-preview-item', 'services__subject'],
    ['subject-detail-visible', 'services__detail--visible'],
    ['subject-detail-close', 'services__detail-close'],
    ['subject-detail-title', 'services__detail-title'],
    ['subject-detail-text', 'services__detail-text'],
    ['subjects-preview-hint', 'services__subjects-hint'],
    ['services-description', 'services__lead'],
    ['service-card-dark', 'services__card--dark'],
    ['service-card-accent', 'services__card--accent'],
    ['events-more-wrapper--visible', 'events__more--visible'],
    ['events-more-wrapper--hidden', 'events__more--hidden'],
    ['events-more-container', 'events__more-bar'],
    ['events-more-inner', 'events__more-inner'],
    ['events-more-wrapper', 'events__more'],
    ['slider-container', 'slider__container'],
    ['hero-image-wrapper', 'hero__figure'],
    ['about-emojis-bg', 'about__emojis'],
    ['stat-label-accent', 'stats__label-accent'],
    ['faq-question-heading', 'faq__question-text'],
    ['schedule-container', 'schedule__layout'],
    ['document-actions', 'documents__actions'],
    ['event-card--tablet-only', 'events__card--tablet-only'],
    ['lightbox-caption', 'lightbox__caption'],
    ['lightbox-content', 'lightbox__content'],
    ['lightbox-slider', 'lightbox__slider'],
    ['lightbox-slides', 'lightbox__slides'],
    ['lightbox-close', 'lightbox__close'],
    ['lightbox-prev', 'lightbox__prev'],
    ['lightbox-next', 'lightbox__next'],
    ['lightbox-dots', 'lightbox__dots'],
    ['nav-cta-mobile', 'site-header__item--cta-mobile'],
    ['dropdown-menu', 'site-header__submenu'],
    ['header-cta-btn', 'site-header__cta'],
    ['menu-toggle', 'site-header__toggle'],
    ['nav-dropdown', 'site-header__dropdown'],
    ['nav-links', 'site-header__list'],
    ['form-group-checkbox', 'contact-form__consent'],
    ['about-icon-right', 'about__icon--right'],
    ['about-icon-left', 'about__icon--left'],
    ['about-icon-top', 'about__icon--top'],
    ['about-icon-bottom', 'about__icon--bottom'],
    ['hero-description', 'hero__description'],
    ['hero-buttons', 'hero__actions'],
    ['hero-content', 'hero__content'],
    ['hero-wrapper', 'hero__wrapper'],
    ['hero-image', 'hero__media'],
    ['hero-photo', 'hero__photo'],
    ['services-container', 'services__inner'],
    ['services-header', 'services__header'],
    ['services-title', 'services__title'],
    ['events-description', 'events__lead'],
    ['events-container', 'events__inner'],
    ['events-header', 'events__header'],
    ['events-title', 'events__title'],
    ['contact-container', 'contact__inner'],
    ['faq-container', 'faq__list'],
    ['slider-controls', 'slider__controls'],
    ['slider-arrow', 'slider__arrow'],
    ['slider-dot', 'slider__dot'],
    ['document-icon', 'documents__icon'],
    ['document-card', 'documents__card'],
    ['documents-grid', 'documents__grid'],
    ['service-card', 'services__card'],
    ['service-icon', 'services__card-icon'],
    ['service-link', 'services__card-link'],
    ['teacher-profile', 'about__profile'],
    ['teacher-photo', 'about__photo'],
    ['teacher-name', 'about__name'],
    ['review-author', 'reviews__author'],
    ['schedule-contact', 'schedule__contact'],
    ['schedule-calendar', 'schedule__calendar'],
    ['section-title', 'section__title'],
    ['stat-label', 'stats__label'],
    ['stat-number', 'stats__value'],
    ['stat-item', 'stats__item'],
    ['stats-grid', 'stats__grid'],
    ['review-text', 'reviews__text'],
    ['review-icon', 'reviews__icon'],
    ['review-card', 'reviews__card'],
    ['reviews-grid', 'reviews__grid'],
    ['schedule-note', 'schedule__note'],
    ['schedule-item', 'schedule__item'],
    ['schedule-info', 'schedule__info'],
    ['faq-question', 'faq__question'],
    ['faq-answer', 'faq__answer'],
    ['form-message', 'contact-form__message'],
    ['submit-btn', 'contact-form__submit'],
    ['lightbox-dot', 'lightbox__dot'],
    ['lightbox-slide', 'lightbox__slide'],
    ['btn-telegram', 'btn--telegram'],
    ['btn-secondary', 'btn--secondary'],
    ['btn-primary', 'btn--primary'],
    ['services-grid', 'services__grid'],
    ['event-overlay', 'events__overlay'],
    ['event-card', 'events__card'],
    ['events-grid', 'events__grid'],
    ['form-group', 'contact-form__field'],
    ['contact-form', 'contact__form'],
    ['about-icons', 'about__icons'],
    ['about-icon', 'about__icon'],
    ['faq-item', 'faq__item'],
    ['doc-btn', 'documents__btn'],
    ['subjects-preview', 'services__subjects'],
    ['subject-detail', 'services__detail'],
    ['nav .nav-links', '.site-header__nav .site-header__list'],
    ['nav .logo', '.site-header__nav .site-header__logo'],
    ['a.logo:hover', 'a.site-header__logo:hover'],
    ['.logo', '.site-header__logo'],
    ['nav {', '.site-header__nav {'],
    ['body > header', '.site-header'],
    ['.container', '.layout__container'],
    ['class="container"', 'class="layout__container"'],
    ['class="slider"', 'class="slider__track"'],
    ['class="slide"', 'class="slider__slide"'],
    ['class="bio"', 'class="about__bio"'],
    ['    <header>', '    <header class="site-header">'],
    ['.slider {', '.slider__track {'],
    ['.slide {', '.slider__slide {'],
    ['.slide img', '.slider__slide img'],
    ['.nav-links.active', '.site-header__list--open'],
    ['.nav-links > li > a', '.site-header__list > li > a'],
    ['.nav-links a:hover', '.site-header__list a:hover'],
    ['.nav-links a.active::after', '.site-header__list a.site-header__link--active::after'],
    ['.nav-links a.active', '.site-header__list a.site-header__link--active'],
    ['.faq-item.active .faq-answer', '.faq__item--open .faq__answer'],
    ['.faq-item.active .faq-question i', '.faq__item--open .faq__question i'],
    ['.faq-item.active', '.faq__item--open'],
    ['.slider__dot.active', '.slider__dot--active'],
    ['.lightbox__dot.active', '.lightbox__dot--active'],
    ['.lightbox-dot.active', '.lightbox__dot--active'],
];

pairs.sort((a, b) => b[0].length - a[0].length);

const files = ['index.html', 'styles/style.css', 'styles/slider.css'];

for (const f of files) {
    const p = path.join(root, f);
    if (!fs.existsSync(p)) continue;
    let s = fs.readFileSync(p, 'utf8');
    const before = s;
    for (const [from, to] of pairs) {
        if (from === to) continue;
        s = s.split(from).join(to);
    }
    if (s !== before) fs.writeFileSync(p, s);
    console.log(f, s !== before ? 'OK' : 'skip');
}
